### ISSUE TITLE
hello,missing file

### ISSUE THREAD

**Issue by yanglilizhang** [Tottowich/YoloTracking#5]
hello! Why is there no requirement document?

**Comment by Tottowich** [comment]
@yanglilizhang requirements.txt has now been added. The previous version was a bit outdated so I recommend updating the project if you're looking to use the sequence verification algorithm.

**Comment by yanglilizhang** [comment]
> @yanglilizhang requirements.txt has now been added. The previous version was a bit outdated so I recommend updating the project if you're looking to use the sequence verification algorithm.

thanks
